# Generated by Django 5.0 on 2023-12-31 08:14

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('doc', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='file',
            name='job',
        ),
        migrations.AddField(
            model_name='file',
            name='job',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='files', to='doc.job'),
        ),
    ]
