# Generated by Django 5.0 on 2023-12-31 08:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('doc', '0002_remove_file_job_file_job'),
    ]

    operations = [
        migrations.AlterField(
            model_name='job',
            name='file',
            field=models.ManyToManyField(related_name='jobs', to='doc.file'),
        ),
    ]
