# Generated by Django 5.0 on 2023-12-31 08:37

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('doc', '0003_alter_job_file'),
    ]

    operations = [
        migrations.AlterField(
            model_name='job',
            name='po_date',
            field=models.DateTimeField(default=datetime.date.today),
        ),
    ]
