# Generated by Django 5.0 on 2023-12-31 11:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('doc', '0005_rename_status_job_project_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='job',
            name='po_date',
            field=models.DateField(),
        ),
    ]
